version: '3.8'

services:
  frontend:
    build: ./apartment-listing-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./apartment-listing-frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./apartment-listing-backend
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/apartments
      - NODE_ENV=development
    volumes:
      - ./apartment-listing-backend:/app
      - /app/node_modules
    command: sh -c "npm run build && npm run start:dev"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 